name: FoliaPlaceholders
version: 1.0.0
main: org.dreeam.expansion.folia.FoliaExpansionPlugin
authors:
  - dreeam
description: PlaceholderAPI expansion for Folia region TPS and MSPT placeholders.
api-version: "1.21"
server:
  dependencies:
    - name: PlaceholderAPI
      required: true
      load: AFTER
      join-classpath: true
provides:
  - PlaceholderAPI
