name: FoliaExpansion
version: 1.0.0
main: org.dreeam.expansion.folia.FoliaExpansionPlugin
api-version: "1.21.4"
folia-supported: true

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
